/* 챔대 장비·공통 수치. 드래곤은 dragons.js에서 로드합니다. */
window.DV1_CHAM_RULES = {
  ACC: [
    {
      ko: "빛뿔 (크/체) 18",
      en: "Horn of light +18 (Crit/HP)",
      hp: 0.08,
      atk: 0,
      def: 0,
    },
    {
      ko: "빛뿔 (크/공) 18",
      en: "Horn of light +18 (Crit/ATK)",
      hp: 0,
      atk: 0.08,
      def: 0,
    },
    {
      ko: "빛뿔 (크/방) 18",
      en: "Horn of light +18 (Crit/DEF)",
      hp: 0,
      atk: 0,
      def: 0.08,
    },
    {
      ko: "빛뿔 (크/체) 20",
      en: "Horn of light +20 (Crit/HP)",
      hp: 0.1,
      atk: 0,
      def: 0,
    },
    {
      ko: "빛뿔 (크/공) 20",
      en: "Horn of light +20 (Crit/ATK)",
      hp: 0,
      atk: 0.1,
      def: 0,
    },
    {
      ko: "빛뿔 (크/방) 20",
      en: "Horn of light +20 (Crit/DEF)",
      hp: 0,
      atk: 0,
      def: 0.1,
    },
    {
      ko: "악몽 수호자의 보주 (악보) 16",
      en: "Nightmare Orb +16 (HP)",
      hp: 0.16,
      atk: 0,
      def: 0,
    },
    {
      ko: "황혼 수호자의 보주 (황보) 16",
      en: "Dusk Orb +16 (ATK)",
      hp: 0,
      atk: 0.16,
      def: 0,
    },
    {
      ko: "여명 수호자의 보주 (여보) 16",
      en: "Dawn Orb +16 (DEF)",
      hp: 0,
      atk: 0,
      def: 0.16,
    },
    {
      ko: "물뿔 (체/공) 16",
      en: "Horn of water +16 (HP/ATK)",
      hp: 0.1,
      atk: 0.06,
      def: 0,
    },
    {
      ko: "물뿔 (체/방) 16",
      en: "Horn of water +16 (HP/DEF)",
      hp: 0.1,
      atk: 0,
      def: 0.06,
    },
    {
      ko: "불뿔 (공/체) 16",
      en: "Horn of fire +16 (ATK/HP)",
      hp: 0.06,
      atk: 0.1,
      def: 0,
    },
    {
      ko: "불뿔 (공/방) 16",
      en: "Horn of fire +16 (ATK/DEF)",
      hp: 0,
      atk: 0.1,
      def: 0.06,
    },
    {
      ko: "대뿔 (방/체) 16",
      en: "Horn of earth +16 (DEF/HP)",
      hp: 0.06,
      atk: 0,
      def: 0.1,
    },
    {
      ko: "대뿔 (방/공) 16",
      en: "Horn of earth +16 (DEF/ATK)",
      hp: 0,
      atk: 0.06,
      def: 0.1,
    },
    {
      ko: "바뿔 (체/방) 16",
      en: "Horn of wind +16 (HP/DEF)",
      hp: 0.08,
      atk: 0,
      def: 0.08,
    },
    {
      ko: "바뿔 (공/체) 16",
      en: "Horn of wind +16 (ATK/HP)",
      hp: 0.08,
      atk: 0.08,
      def: 0,
    },
    {
      ko: "바뿔 (공/방) 16",
      en: "Horn of wind +16 (ATK/DEF)",
      hp: 0,
      atk: 0.08,
      def: 0.08,
    },
    {
      ko: "악몽 수호자의 보주 (악보) 17",
      en: "Nightmare Orb +17 (HP)",
      hp: 0.17,
      atk: 0,
      def: 0,
    },
    {
      ko: "황혼 수호자의 보주 (황보) 17",
      en: "Dusk Orb +17 (ATK)",
      hp: 0,
      atk: 0.17,
      def: 0,
    },
    {
      ko: "여명 수호자의 보주 (여보) 17",
      en: "Dawn Orb +17 (DEF)",
      hp: 0,
      atk: 0,
      def: 0.17,
    },
    {
      ko: "물뿔 (체/공) 17",
      en: "Horn of water +17 (HP/ATK)",
      hp: 0.11,
      atk: 0.06,
      def: 0,
    },
    {
      ko: "물뿔 (체/방) 17",
      en: "Horn of water +17 (HP/DEF)",
      hp: 0.11,
      atk: 0,
      def: 0.06,
    },
    {
      ko: "불뿔 (공/체) 17",
      en: "Horn of fire +17 (ATK/HP)",
      hp: 0.06,
      atk: 0.11,
      def: 0,
    },
    {
      ko: "불뿔 (공/방) 17",
      en: "Horn of fire +17 (ATK/DEF)",
      hp: 0,
      atk: 0.11,
      def: 0.06,
    },
    {
      ko: "대뿔 (방/체) 17",
      en: "Horn of earth +17 (DEF/HP)",
      hp: 0.06,
      atk: 0,
      def: 0.11,
    },
    {
      ko: "대뿔 (방/공) 17",
      en: "Horn of earth +17 (DEF/ATK)",
      hp: 0,
      atk: 0.06,
      def: 0.11,
    },
    {
      ko: "바뿔 (체/방) 17",
      en: "Horn of wind +17 (HP/DEF)",
      hp: 0.09,
      atk: 0,
      def: 0.08,
    },
    {
      ko: "바뿔 (공/체) 17",
      en: "Horn of wind +17 (ATK/HP)",
      hp: 0.08,
      atk: 0.09,
      def: 0,
    },
    {
      ko: "바뿔 (공/방) 17",
      en: "Horn of wind +17 (ATK/DEF)",
      hp: 0,
      atk: 0.09,
      def: 0.08,
    },
    {
      ko: "악몽 수호자의 보주 (악보) 18",
      en: "Nightmare Orb +18 (HP)",
      hp: 0.18,
      atk: 0,
      def: 0,
    },
    {
      ko: "황혼 수호자의 보주 (황보) 18",
      en: "Dusk Orb +18 (ATK)",
      hp: 0,
      atk: 0.18,
      def: 0,
    },
    {
      ko: "여명 수호자의 보주 (여보) 18",
      en: "Dawn Orb +18 (DEF)",
      hp: 0,
      atk: 0,
      def: 0.18,
    },
    {
      ko: "물뿔 (체/공) 18",
      en: "Horn of water +18 (HP/ATK)",
      hp: 0.12,
      atk: 0.06,
      def: 0,
    },
    {
      ko: "물뿔 (체/방) 18",
      en: "Horn of water +18 (HP/DEF)",
      hp: 0.12,
      atk: 0,
      def: 0.06,
    },
    {
      ko: "불뿔 (공/체) 18",
      en: "Horn of fire +18 (ATK/HP)",
      hp: 0.06,
      atk: 0.12,
      def: 0,
    },
    {
      ko: "불뿔 (공/방) 18",
      en: "Horn of fire +18 (ATK/DEF)",
      hp: 0,
      atk: 0.12,
      def: 0.06,
    },
    {
      ko: "대뿔 (방/체) 18",
      en: "Horn of earth +18 (DEF/HP)",
      hp: 0.06,
      atk: 0,
      def: 0.12,
    },
    {
      ko: "대뿔 (방/공) 18",
      en: "Horn of earth +18 (DEF/ATK)",
      hp: 0,
      atk: 0.06,
      def: 0.12,
    },
    {
      ko: "바뿔 (체/방) 18",
      en: "Horn of wind +18 (HP/DEF)",
      hp: 0.09,
      atk: 0,
      def: 0.09,
    },
    {
      ko: "바뿔 (공/체) 18",
      en: "Horn of wind +18 (ATK/HP)",
      hp: 0.09,
      atk: 0.09,
      def: 0,
    },
    {
      ko: "바뿔 (공/방) 18",
      en: "Horn of wind +18 (ATK/DEF)",
      hp: 0,
      atk: 0.09,
      def: 0.09,
    },
    {
      ko: "악몽 수호자의 보주 (악보) 19",
      en: "Nightmare Orb +19 (HP)",
      hp: 0.19,
      atk: 0,
      def: 0,
    },
    {
      ko: "황혼 수호자의 보주 (황보) 19",
      en: "Dusk Orb +19 (ATK)",
      hp: 0,
      atk: 0.19,
      def: 0,
    },
    {
      ko: "여명 수호자의 보주 (여보) 19",
      en: "Dawn Orb +19 (DEF)",
      hp: 0,
      atk: 0,
      def: 0.19,
    },
    {
      ko: "물뿔 (체/공) 19",
      en: "Horn of water +19 (HP/ATK)",
      hp: 0.13,
      atk: 0.06,
      def: 0,
    },
    {
      ko: "물뿔 (체/방) 19",
      en: "Horn of water +19 (HP/DEF)",
      hp: 0.13,
      atk: 0,
      def: 0.06,
    },
    {
      ko: "불뿔 (공/체) 19",
      en: "Horn of fire +19 (ATK/HP)",
      hp: 0.06,
      atk: 0.13,
      def: 0,
    },
    {
      ko: "불뿔 (공/방) 19",
      en: "Horn of fire +19 (ATK/DEF)",
      hp: 0,
      atk: 0.13,
      def: 0.06,
    },
    {
      ko: "대뿔 (방/체) 19",
      en: "Horn of earth +19 (DEF/HP)",
      hp: 0.06,
      atk: 0,
      def: 0.13,
    },
    {
      ko: "대뿔 (방/공) 19",
      en: "Horn of earth +19 (DEF/ATK)",
      hp: 0,
      atk: 0.06,
      def: 0.13,
    },
    {
      ko: "바뿔 (체/방) 19",
      en: "Horn of wind +19 (HP/DEF)",
      hp: 0.1,
      atk: 0,
      def: 0.09,
    },
    {
      ko: "바뿔 (공/체) 19",
      en: "Horn of wind +19 (ATK/HP)",
      hp: 0.09,
      atk: 0.1,
      def: 0,
    },
    {
      ko: "바뿔 (공/방) 19",
      en: "Horn of wind +19 (ATK/DEF)",
      hp: 0,
      atk: 0.1,
      def: 0.09,
    },
    {
      ko: "악몽 수호자의 보주 (악보) 20",
      en: "Nightmare Orb +20 (HP)",
      hp: 0.2,
      atk: 0,
      def: 0,
    },
    {
      ko: "황혼 수호자의 보주 (황보) 20",
      en: "Dusk Orb +20 (ATK)",
      hp: 0,
      atk: 0.2,
      def: 0,
    },
    {
      ko: "여명 수호자의 보주 (여보) 20",
      en: "Dawn Orb +20 (DEF)",
      hp: 0,
      atk: 0,
      def: 0.2,
    },
    {
      ko: "물뿔 (체/공) 20",
      en: "Horn of water +20 (HP/ATK)",
      hp: 0.14,
      atk: 0.06,
      def: 0,
    },
    {
      ko: "물뿔 (체/방) 20",
      en: "Horn of water +20 (HP/DEF)",
      hp: 0.14,
      atk: 0,
      def: 0.06,
    },
    {
      ko: "불뿔 (공/체) 20",
      en: "Horn of fire +20 (ATK/HP)",
      hp: 0.06,
      atk: 0.14,
      def: 0,
    },
    {
      ko: "불뿔 (공/방) 20",
      en: "Horn of fire +20 (ATK/DEF)",
      hp: 0,
      atk: 0.14,
      def: 0.06,
    },
    {
      ko: "대뿔 (방/체) 20",
      en: "Horn of earth +20 (DEF/HP)",
      hp: 0.06,
      atk: 0,
      def: 0.14,
    },
    {
      ko: "대뿔 (방/공) 20",
      en: "Horn of earth +20 (DEF/ATK)",
      hp: 0,
      atk: 0.06,
      def: 0.14,
    },
    {
      ko: "바뿔 (체/방) 20",
      en: "Horn of wind +20 (HP/DEF)",
      hp: 0.1,
      atk: 0,
      def: 0.1,
    },
    {
      ko: "바뿔 (공/체) 20",
      en: "Horn of wind +20 (ATK/HP)",
      hp: 0.1,
      atk: 0.1,
      def: 0,
    },
    {
      ko: "바뿔 (공/방) 20",
      en: "Horn of wind +20 (ATK/DEF)",
      hp: 0,
      atk: 0.1,
      def: 0.1,
    },
  ],
  BASE: {
    "7.0": {
      "체력형": {
        hp: 1252,
        atk: 176,
        def: 176,
      },
      "공격형": {
        hp: 876,
        atk: 285,
        def: 161,
      },
      "방어형": {
        hp: 788,
        atk: 185,
        def: 283,
      },
      "공방형": {
        hp: 720,
        atk: 242,
        def: 243,
      },
      "체공형": {
        hp: 1080,
        atk: 262,
        def: 133,
      },
      "체방형": {
        hp: 1080,
        atk: 133,
        def: 262,
      },
    },
    "8.0": {
      "체력형": {
        hp: 1332,
        atk: 176,
        def: 176,
      },
      "공격형": {
        hp: 876,
        atk: 305,
        def: 161,
      },
      "방어형": {
        hp: 788,
        atk: 185,
        def: 303,
      },
      "공방형": {
        hp: 720,
        atk: 252,
        def: 253,
      },
      "체공형": {
        hp: 1120,
        atk: 272,
        def: 133,
      },
      "체방형": {
        hp: 1120,
        atk: 133,
        def: 272,
      },
    },
    "9.0": {
      "체력형": {
        hp: 1412,
        atk: 176,
        def: 176,
      },
      "공격형": {
        hp: 876,
        atk: 325,
        def: 161,
      },
      "방어형": {
        hp: 788,
        atk: 185,
        def: 323,
      },
      "공방형": {
        hp: 720,
        atk: 262,
        def: 263,
      },
      "체공형": {
        hp: 1160,
        atk: 282,
        def: 133,
      },
      "체방형": {
        hp: 1160,
        atk: 133,
        def: 282,
      },
    },
  },
  POTION: [
    {
      ko: "크리•회피",
      en: "Crit/Evade",
      hp: 24,
      atk: 6,
      def: 6,
    },
    {
      ko: "체8",
      en: "HP 8",
      hp: 120,
      atk: 6,
      def: 6,
    },
    {
      ko: "공8",
      en: "ATK 8",
      hp: 24,
      atk: 30,
      def: 6,
    },
    {
      ko: "방8",
      en: "DEF 8",
      hp: 24,
      atk: 6,
      def: 30,
    },
    {
      ko: "체7",
      en: "HP 7",
      hp: 108,
      atk: 6,
      def: 6,
    },
    {
      ko: "공7",
      en: "ATK 7",
      hp: 24,
      atk: 27,
      def: 6,
    },
    {
      ko: "방7",
      en: "DEF 7",
      hp: 24,
      atk: 6,
      def: 27,
    },
    {
      ko: "체6",
      en: "HP 6",
      hp: 96,
      atk: 6,
      def: 6,
    },
    {
      ko: "공6",
      en: "ATK 6",
      hp: 24,
      atk: 24,
      def: 6,
    },
    {
      ko: "방6",
      en: "DEF 6",
      hp: 24,
      atk: 6,
      def: 24,
    },
    {
      ko: "체5",
      en: "HP 5",
      hp: 84,
      atk: 6,
      def: 6,
    },
    {
      ko: "공5",
      en: "ATK 5",
      hp: 24,
      atk: 21,
      def: 6,
    },
    {
      ko: "방5",
      en: "DEF 5",
      hp: 24,
      atk: 6,
      def: 21,
    },
    {
      ko: "체4",
      en: "HP 4",
      hp: 72,
      atk: 6,
      def: 6,
    },
    {
      ko: "공4",
      en: "ATK 4",
      hp: 24,
      atk: 18,
      def: 6,
    },
    {
      ko: "방4",
      en: "DEF 4",
      hp: 24,
      atk: 6,
      def: 18,
    },
    {
      ko: "체3",
      en: "HP 3",
      hp: 60,
      atk: 6,
      def: 6,
    },
    {
      ko: "공3",
      en: "ATK 3",
      hp: 24,
      atk: 15,
      def: 6,
    },
    {
      ko: "방3",
      en: "DEF 3",
      hp: 24,
      atk: 6,
      def: 15,
    },
    {
      ko: "체2",
      en: "HP 2",
      hp: 48,
      atk: 6,
      def: 6,
    },
    {
      ko: "공2",
      en: "ATK 2",
      hp: 24,
      atk: 12,
      def: 6,
    },
    {
      ko: "방2",
      en: "DEF 2",
      hp: 24,
      atk: 6,
      def: 12,
    },
    {
      ko: "체1",
      en: "HP 1",
      hp: 36,
      atk: 6,
      def: 6,
    },
    {
      ko: "공1",
      en: "ATK 1",
      hp: 24,
      atk: 9,
      def: 6,
    },
    {
      ko: "방1",
      en: "DEF 1",
      hp: 24,
      atk: 6,
      def: 9,
    },
    {
      ko: "자양강장제S",
      en: "Tonic S",
      hp: 24,
      atk: 6,
      def: 6,
    },
  ],
};
